"""empty message

Revision ID: 2d2422cf9bf2
Revises: 6d74b76282fb
Create Date: 2019-09-04 22:06:35.591000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2422cf9bf2'
down_revision = '6d74b76282fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'admin')
    # ### end Alembic commands ###
