"""empty message

Revision ID: 403b9f4cc7b2
Revises: dfc2b21b2715
Create Date: 2019-09-04 14:47:00.243000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403b9f4cc7b2'
down_revision = 'dfc2b21b2715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sipuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.Integer(), nullable=True),
    sa.Column('sipuser', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('caller', sa.String(length=50), nullable=True),
    sa.Column('callee', sa.String(length=50), nullable=True),
    sa.Column('callmethod', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.Column('buuid', sa.String(length=50), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.Column('isbleg', sa.Boolean(), nullable=True),
    sa.Column('uptime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sipuser')
    # ### end Alembic commands ###
