"""empty message

Revision ID: 6d74b76282fb
Revises: b50cebbd944e
Create Date: 2019-09-04 18:30:33.015000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d74b76282fb'
down_revision = 'b50cebbd944e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('company', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('company', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.drop_column('company', 'uptime')
    op.add_column('sipuser', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('sipuser', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.drop_column('sipuser', 'uptime')
    op.add_column('user', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.drop_column('user', 'uptime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uptime', mysql.DATETIME(), nullable=True))
    op.drop_column('user', 'update_time')
    op.drop_column('user', 'create_time')
    op.add_column('sipuser', sa.Column('uptime', mysql.DATETIME(), nullable=True))
    op.drop_column('sipuser', 'update_time')
    op.drop_column('sipuser', 'create_time')
    op.add_column('company', sa.Column('uptime', mysql.DATETIME(), nullable=True))
    op.drop_column('company', 'update_time')
    op.drop_column('company', 'status')
    op.drop_column('company', 'create_time')
    # ### end Alembic commands ###
