"""empty message

Revision ID: b6ae32f626ee
Revises: 860f85f84387
Create Date: 2019-09-04 16:34:38.580000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6ae32f626ee'
down_revision = '860f85f84387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sipuser')
    op.add_column('user', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'company', ['company_id'], ['id'])
    op.drop_column('user', 'company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(u'user_ibfk_1', 'user', 'company', ['company'], ['id'])
    op.drop_column('user', 'company_id')
    op.create_table('sipuser',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('company', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sipuser', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('caller', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('callee', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('callmethod', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('direction', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('uuid', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('buuid', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('state', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('isbleg', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('uptime', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['company'], [u'company.id'], name=u'sipuser_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
